<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenInternalTestSuite2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>d178afd9-b515-45f5-8bc2-c935aba950f3</testSuiteGuid>
   <testCaseLink>
      <guid>5505fcf1-099f-4f89-9a16-98aebce2d61a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo1/TestDataInternalTC2</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd3b3ed0-3ab1-47e5-8435-7efaef279fd6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataLoginInternal2</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dd3b3ed0-3ab1-47e5-8435-7efaef279fd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>USERNAME</value>
         <variableId>f4337fdf-f44c-4957-b574-f961b11497be</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd3b3ed0-3ab1-47e5-8435-7efaef279fd6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>PASSWORD</value>
         <variableId>c70a550b-29da-42a0-8919-f96c954776d0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
